### ISSUE TITLE
php artisan module:make-filament-page get always generated in App\Filament namespace and folder

### ISSUE THREAD

**Issue by eelco2k** [RealMrHex/filament-modular-v3#7]
Posted the issue in wrong github repository:

but this is the issue: 

https://github.com/RealMrHex/filament-modular/issues/13

**Comment by syzygyinteractivemedia** [comment]
PR is here: 

https://github.com/RealMrHex/filament-modular-v3/pull/8

**Comment by mohaphez** [comment]
Thanks for your contribution ! :heart:

**Comment by syzygyinteractivemedia** [comment]
You’re welcome! ☺️
